import unittest
import shutil
from pathlib import Path
from agent.config_schema import AgentConfig, AuthConfig, EncryptionConfig
from agent.platforms.macos import MacOSAgent
import logging

class TestMacOSAgent(unittest.TestCase):
    def setUp(self):
        self.base_dir = Path("test_output_mac").resolve()
        self.base_dir.mkdir(exist_ok=True)
        self.logger = logging.getLogger("TestMacOS")
        
        from agent.config_schema import ConnectionConfig
        conn = ConnectionConfig(
            name="MacConn",
            mode="transport",
            ike_version="ikev2",
            auth=AuthConfig(type="psk", value="MacSecret"),
            encryption=EncryptionConfig(ike="default", esp="default"),
            local_subnets=["10.0.0.0/24"],
            remote_subnets=["192.168.1.0/24"],
            protocol="udp",
            local_port="500",
            remote_port="500",
            lifetime_minutes=60
        )
        self.config = AgentConfig(
            connections=[conn],
            logging_level="info"
        )

    def tearDown(self):
        if self.base_dir.exists():
            shutil.rmtree(self.base_dir)

    def test_generate_config_and_paths(self):
        agent = MacOSAgent(self.config, self.base_dir, self.logger)
        
        # Verify it fell back to local dir since we are on Windows
        self.assertTrue(str(agent.conf_dir).startswith(str(self.base_dir)))
        
        conf = agent._generate_swanctl_conf()
        print("\nGenerated Mac Config:\n" + conf)
        
        self.assertIn("# Generated by Unified IPsec Agent (MacOS)", conf)
        self.assertIn("esp_proposals = aes256-sha256", conf) # Default expansion
        self.assertIn('secret = "MacSecret"', conf)

if __name__ == '__main__':
    unittest.main()
